#!/bin/bash

echo 'Calling mvn clean install'
mvn clean install


if [ "$?" = "0" ]; then
  echo 'cleaning the old docker springrestjpa:0.1 image'
  docker rmi -f springrestjpa:0.1
  
  echo 'calling docker build -t springrestjpa:0.1 -f Dockerfile-app'
  docker build -t springrestjpa:0.1 -f Dockerfile-app .

  echo 'build finished'
else
  echo "Error during the build!"
  exit 1
fi

