version: '2'
services:
 lb:
  image: dockercloud/haproxy:1.2.1
  links:
   - springrestjpa
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
  ports:
   - 80:80
 springrestjpa:
  image: springrestjpa:0.1
  command: dockerize -timeout 600s -wait tcp://database:3306 /bin/bash catalina.sh run
  depends_on:
   - database
   - terracotta-server
  links:
   - database:database
   - terracotta-server:terracotta-server
 database:
  image: database:0.1
 terracotta-server:
  image: terracotta-server:0.1

